image: openjdk:14-jdk-buster

stages:
  - build
  - visualize
  - deploy
  - release

build-api:
  stage: build
  before_script:
    - apt-get update && apt-get install -y nodejs npm && npm install -g gulp
    - chmod u+x api/gradlew
  script:
    - cd api && ./gradlew build
  artifacts:
    expire_in: 1h
    paths:
      - api/build/libs/api.jar
      - api/build/reports/jacoco/test/jacocoTestReport.xml

coverage-jdk11:
  stage: visualize
  image: haynes/jacoco2cobertura:1.0.4
  script:
    - 'python /opt/cover2cover.py api/build/reports/jacoco/test/jacocoTestReport.xml api/src/main/java > api/build/reports/cobertura.xml'
    - 'python /opt/source2filename.py api/build/reports/cobertura.xml'
  needs: ["build-api"]
  dependencies:
    - build-api
  artifacts:
    reports:
      cobertura: api/build/reports/cobertura.xml

docker-latest:
  stage: deploy
  image: docker:19.03.11
  services:
    - docker:dind
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - docker build -t dedicatedcode/paperspace-search:latest search/
    - docker build -t dedicatedcode/paperspace:latest api/
    - docker push dedicatedcode/paperspace:latest
    - docker push dedicatedcode/paperspace-search:latest
  only:
    refs:
      - master
  except:
    - tags

copy-artifacts:
  stage: release
  image: alpine:3.9
  script:
    - export LC_ALL=en_US.UTF-8
    - export LANG=en_US.UTF-8
    - apk add py-pip unzip curl autoconf libtool automake bash lcms2-dev
    - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
    - unzip awscli-bundle.zip
    - ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY
    - aws configure set aws_secret_access_key $AWS_SECRET
    - mkdir -p tmp/paperspace-app && cp api/build/libs/api.jar tmp/paperspace-app/app.jar
    - cd tmp/ && tar -zcvf paperspace-$CI_COMMIT_TAG.tgz paperspace-app && cd ..
    - aws s3 cp tmp/paperspace-$CI_COMMIT_TAG.tgz s3://$BUCKET_NAME/paperspace-$CI_COMMIT_TAG.tgz
  only:
    - tags
docker-release:
  stage: release
  image: docker:19.03.11
  services:
    - docker:dind
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - docker build -t dedicatedcode/paperspace-search:$CI_COMMIT_TAG search/
    - docker build -t dedicatedcode/paperspace:$CI_COMMIT_TAG api/
    - docker push dedicatedcode/paperspace:$CI_COMMIT_TAG
    - docker push dedicatedcode/paperspace-search:$CI_COMMIT_TAG
  only:
    - tags
