image: openjdk:14

stages:
  - build
  - deploy

build-api:
  stage: build
  before_script:
    - chmod u+x api/mvnw
  script:
    - cd api && ./mvnw package
  artifacts:
    paths:
      - api/target/api.jar

build-feeder:
  stage: build
  before_script:
    - chmod u+x feeder/mvnw
  script:
    - cd feeder && ./mvnw package
  artifacts:
    paths:
      - feeder/target/feeder.jar

docker-latest:
  stage: deploy
  image: docker:19.03.11
  before_script:
    - docker info
  script:
    - docker build -t dedicatedcode/paperspace-search:latest search/
    - docker build -t dedicatedcode/paperspace-feeder:latest feeder/
    - docker build -t dedicatedcode/paperspace:latest api/
