image: openjdk:14

stages:
  - build
  - deploy

build-api:
  stage: build
  before_script:
    - chmod u+x api/mvnw
  script:
    - cd api && ./mvnw package
  artifacts:
    paths:
      - api/target/api.jar

build-feeder:
  stage: build
  before_script:
    - chmod u+x feeder/mvnw
  script:
    - cd feeder && ./mvnw package
  artifacts:
    paths:
      - feeder/target/feeder.jar

docker-latest:
  stage: deploy
  image: docker:19.03.11
  services:
    - docker:dind
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - docker build -t dedicatedcode/paperspace-search:latest search/
    - docker build -t dedicatedcode/paperspace-feeder:latest feeder/
    - docker build -t dedicatedcode/paperspace:latest api/
    - docker push dedicatedcode/paperspace:latest
    - docker push dedicatedcode/paperspace-search:latest
    - docker push dedicatedcode/paperspace-feeder:latest
