image: openjdk:14

stages:
  - build
  - deploy
  - release

build-api:
  stage: build
  before_script:
    - chmod u+x api/mvnw
  script:
    - cd api && ./mvnw package
  artifacts:
    expire_in: 1h
    paths:
      - api/target/api.jar

build-feeder:
  stage: build
  before_script:
    - chmod u+x feeder/mvnw
  script:
    - cd feeder && ./mvnw package
  artifacts:
    expire_in: 1h
    paths:
      - feeder/target/feeder.jar

docker-latest:
  stage: deploy
  image: docker:19.03.11
  services:
    - docker:dind
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - docker build -t dedicatedcode/paperspace-search:latest search/
    - docker build -t dedicatedcode/paperspace-feeder:latest feeder/
    - docker build -t dedicatedcode/paperspace:latest api/
    - docker push dedicatedcode/paperspace:latest
    - docker push dedicatedcode/paperspace-search:latest
    - docker push dedicatedcode/paperspace-feeder:latest
  except:
    - tags

copy-artifacts:
  stage: release
  image: alpine:3.9
  script:
    - export LC_ALL=en_US.UTF-8
    - export LANG=en_US.UTF-8
    - apk add py-pip unzip curl autoconf libtool automake bash lcms2-dev
    - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
    - unzip awscli-bundle.zip
    - ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY
    - aws configure set aws_secret_access_key $AWS_SECRET
    - mkdir -p tmp/paperspace-app && cp api/target/api.jar tmp/paperspace-app/app.jar
    - mkdir -p tmp/paperspace-feeder && cp feeder/target/feeder.jar tmp/paperspace-feeder/feeder.jar
    - cd tmp/ && tar czf paperspace-$CI_COMMIT_TAG.tgz && cd ..
    - aws s3 cp tmp/paperspace-$CI_COMMIT_TAG.tgz s3://$BUCKET_NAME/paperspace-$CI_COMMIT_TAG.tgz
  only:
    - tags
docker-release:
  stage: release
  image: docker:19.03.11
  services:
    - docker:dind
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - docker build -t dedicatedcode/paperspace-search:$CI_COMMIT_TAG search/
    - docker build -t dedicatedcode/paperspace-feeder:$CI_COMMIT_TAG feeder/
    - docker build -t dedicatedcode/paperspace:$CI_COMMIT_TAG api/
    - docker push dedicatedcode/paperspace:$CI_COMMIT_TAG
    - docker push dedicatedcode/paperspace-search:$CI_COMMIT_TAG
    - docker push dedicatedcode/paperspace-feeder:$CI_COMMIT_TAG
  only:
    - tags
