version: "3.4"
services:
  api:
    image: dedicatedcode/paperspace:latest
    depends_on:
      - search
    restart: unless-stopped
    environment:
      OCR_LANGUAGE: 'deu'
      APPLICATION_HOST: 'REPLACE WITH HOSTNAME OR IP'
      ENABLE_MAIL: 'true'
      MAIL_TO_ADDRESS: 'REPLACE WITH EMAIL ADDRESS'
      MAIL_FROM_ADDRESS: 'REPLACE WITH EMAIL ADDRESS'
      MAIL_ATTACH_DOCUMENTS: 'false'
      MAILING_HOST: 'REPLACE WITH MAIL SERVER HOST'
      MAILING_PORT: 'REPLACE WITH MAIL SERVER PORT'
      MAILING_PROTOCOL: 'smtp'
      MAILING_SMTP_AUTH: 'true'
      MAILING_SMTP_USE_STARTTLS: 'true'
      MAILING_USERNAME: 'REPLACE WITH MAIL SERVER USERNAME'
      MAILING_PASSWORD: 'REPLACE WITH MAIL SERVER PASSWORD'
    volumes:
      - paperspace:/storage
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    ports:
      - 8080:8080
  ftp:
    image: wildscamp/vsftpd
    restart: unless-stopped
    environment:
      PASV_ADDRESS: 'REPLACE WITH FTP IP OR HOSTNAME'
      VSFTPD_USER_1: 'scanner:password:9876:'
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - paperspace:/home/virtual/scanner/data

  search:
    image: dedicatedcode/paperspace-search:latest
    restart: unless-stopped
    volumes:
      - paperspace-search:/data/solr
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8983/solr/documents/admin/ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  paperspace:
  paperspace-search: