version: "3.4"
services:
  api:
    image: dedicatedcode/paperspace:v3.0.1
    depends_on:
      - search
    restart: unless-stopped
    environment:
      OCR_LANGUAGE: 'deu'
      APPLICATION_HOST: 'http://localhost:8080'
    volumes:
      - paperspace:/storage
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    ports:
      - 8080:8080
  search:
    image: dedicatedcode/paperspace-search:v3.0.1
    restart: unless-stopped
    volumes:
      - paperspace-search:/data/solr
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8983/solr/documents/admin/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    ports:
      - 8983:8983
volumes:
  paperspace:
  paperspace-search: