version: "3"
services:
  api:
    image: paperspace:latest
    depends_on:
      - db
      - search
    restart: unless-stopped
    environment:
      APPLICATION_HOST: 'http://localhost:8080'
      DB_HOST: 'db'
      DB_PORT: '3306'
      DB_TABLE: '${MYSQL_DATABASE}'
      DB_USER: '${MYSQL_USER}'
      DB_PASSWORD: '${MYSQL_PASSWORD}'
      SEARCH_HOST: 'search'
      SEARCH_PORT: '8983'
      STORAGE_PATH: '/binary'

      ENABLE_MAIL: '${ENABLE_MAIL}'
      MAIL_TO_ADDRESS: '${MAIL_TO_ADDRESS}'
      MAIL_FROM_ADDRESS: '${MAIL_FROM_ADDRESS}'
      MAIL_ATTACH_DOCUMENTS: '${MAIL_ATTACH_DOCUMENTS}'
      MAILING_HOST: '${MAILING_HOST}'
      MAILING_PORT: '${MAILING_PORT}'
      MAILING_PROTOCOL: '${MAILING_PROTOCOL}'
      MAILING_SMTP_AUTH: '${MAILING_SMTP_AUTH}'
      MAILING_SMTP_USE_STARTTLS: '${MAILING_SMTP_USE_STARTTLS}'
      MAILING_USERNAME: '${MAILING_USERNAME}'
      MAILING_PASSWORD: '${MAILING_PASSWORD}'

    volumes:
      - ../data/api/binary:/binary
    ports:
      - 8080:8080
  feeder:
    image: paperspace-feeder:latest
    depends_on:
      - api
    restart: unless-stopped
    environment:
      API_URL: 'http://api:8080'
      DOCUMENT_INPUT: '/data/input/documents'
      DOCUMENT_IGNORED: '/data/ignored/documents'
      DOCUMENT_ERROR: '/data/error/documents'
      DOCUMENT_PROCESSED: '/data/processed/documents'
      DOCUMENT_BACKUP: 'false'
      TASK_INPUT: '/data/input/tasks'
      TASK_IGNORED: '/data/ignored/tasks'
      TASK_ERROR: '/data/errors/tasks'
      TASK_PROCESSED: '/data/processed/tasks'
      TASK_BACKUP: 'false'
      OCR_LANGUAGE: '${OCR_LANGUAGE}'
    volumes:
      - ../data/feeder/task/input:/data/input/tasks
      - ../data/feeder/task/error:/data/errors/tasks
      - ../data/feeder/documents/input:/data/input/documents
      - ../data/feeder/documents/error:/data/errors/documents
  search:
    image: solr:8.5.0
    restart: unless-stopped
    volumes:
      - ./solr/config:/var/solr/data/cores/
      - ../data/solr:/data/solr
    ports:
      - 8983:8983
  db:
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '${SQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - ../data/database:/var/lib/mysql
    ports:
      - 3310:3306