version: "3"
services:
  search:
    image: dedicatedcode/paperspace-search:latest
    restart: unless-stopped
    volumes:
      - ../data/solr:/data/solr
    ports:
    - 8983:8983
  db:
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - ../data/database:/var/lib/mysql
    ports:
      - 3310:3306