version: "3.5"
services:
  search:
    build:
      context: ../search
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8983/solr/documents/admin/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - searchdata:/data/solr
    ports:
    - 8983:8983

volumes:
  searchdata: