version: "3"
services:
  search:
    build:
      context: ../search
    restart: unless-stopped
    volumes:
      - searchdata:/data/solr
    ports:
    - 8983:8983
  db:
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3310:3306

volumes:
  dbdata:
  searchdata: